name: ci-test-simple-form-c#

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
    - name: action checkout code
      uses: actions/checkout@v3

    - name: action setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: run 
      run: dotnet test --no-build --verbosity normal